FROM python:3.11.4-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=app.app
ENV PYTHONPATH=/app

CMD ["celery", "-A", "app.tasks", "worker", "--loglevel=INFO", "-Q", "write_back_queue", "--concurrency=1"]